### ISSUE TITLE
The debug overlay stays in the resulting screenshot

### ISSUE THREAD

**Issue by cbeauche** [neon8100/screenshotter#2]
The debug overlay appears in the resulting screenshot (the demo video says it will not be there)

Tested with 1.0.1, on macOS, Unity 2019.3.9f1

**Comment by neon8100** [comment]
Thanks, if you uncheck "use game view" the screenshot is taken from the camera. This feature was added after the video, as the camera image screenshot caused problems with HDR workflows. For built-in renderer you should be fine using the view from the camera.

I'll eventually add a fix to the "game view" screenshot mode, but disabling that option on the tool should fix it for now.
